dips-ehr-configuration:
  env: 
    CONFIGURATION_SOURCE_URL: https://raw.githubusercontent.com/thorstenbaek/dips-ehr-configuration/master/configuration.json  
  ingress:
    hosts:
      - host: RELEASE-NAME.dips-ehr-configuration.DOMAIN
        paths: 
          - /    
    tls:
      - secretName: configuration-sandbox-tls
        hosts:
          - RELEASE-NAME.dips-ehr-configuration.DOMAIN

dips-ehr-security:
  ingress:
    hosts:
      - host: RELEASE-NAME.dips-ehr-security.DOMAIN
        paths: 
          - /    
    tls:
      - secretName: security-sandbox-tls
        hosts:                  
          - RELEASE-NAME.dips-ehr-security.DOMAIN

dips-ehr-app:
  ingress:
    hosts:
      - host: RELEASE-NAME.dips-ehr-app.DOMAIN
        paths: 
          - /
    tls:
      - secretName: dips-ehr-app-sandbox-tls
        hosts:
          - RELEASE-NAME.dips-ehr-app.DOMAIN

dips-ehr-notes:
  ingress:
    hosts:
      - host: RELEASE-NAME.dips-ehr-notes.DOMAIN
        paths: 
          - /
    tls:
      - secretName: dips-ehr-notes-sandbox-tls
        hosts:
          - RELEASE-NAME.dips-ehr-notes.DOMAIN

nav-pleiepenger:
  ingress:
    hosts:
      - host: RELEASE-NAME.nav-pleiepenger.DOMAIN
        paths: 
          - /
    tls:
      - secretName: nav-pleiepenger-sandbox-tls
        hosts:
          - RELEASE-NAME.nav-pleiepenger.DOMAIN

dips-fhir-service2:
  env:
    ENVIRONMENT: "RELEASE-NAME.dips-ehr-app.DOMAIN"  
    CONNECTION_STRING: "server=postgres-postgresql.postgres.svc.cluster.local;database=fhirbase;user id=postgres;password=postgres;"
    CONFIGURATION_SERVICE_URI: RELEASE-NAME-dips-ehr-configuration    
  ingress:
    hosts:
      - host: RELEASE-NAME.dips.fhir.service.DOMAIN
        paths: 
          - /
    tls:
      - secretName: fhir.service.sandbox-tls
        hosts:
          - RELEASE-NAME.dips.fhir.service.DOMAIN