dips-ehr-configuration:
  env: 
    CONFIGURATION_SOURCE_URL: https://raw.githubusercontent.com/thorstenbaek/dips-ehr-configuration/master/configuration.json  
  ingress:
    hosts:
      - host: dips-ehr-configuration.api.dips.no
        paths: 
          - /    
    tls:
      - secretName: configuration-sandbox-tls
        hosts:
          - dips-ehr-configuration.api.dips.no
          
dips-ehr-security:
  ingress:
    hosts:
      - host: dips-ehr-security.api.dips.no
        paths: 
          - /    
    tls:
      - secretName: security-sandbox-tls
        hosts:
          - dips-ehr-security.api.dips.no

dips-fhir-service:
  env:
    ENVIRONMENT: "dips-ehr-app.api.dips.no"  
    CONFIGURATION_SERVICE_URI: sandbox-dips-ehr-configuration
  ingress:
    hosts:
      - host: dips-fhir-service.api.dips.no
        paths: 
          - /
    tls:
      - secretName: fhir-service-sandbox-tls
        hosts:
          - dips-fhir-service.api.dips.no          
          
dips-ehr-app:
  ingress:
    hosts:
      - host: dips-ehr-app.api.dips.no
        paths: 
          - /
    tls:
      - secretName: dips-ehr-app-sandbox-tls
        hosts:
          - dips-ehr-app.api.dips.no